version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      
    working_directory: /go/src/github.com/gnkz/mnemo
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            chmod +x ${GOPATH}/bin/dep
            ${GOPATH}/bin/dep ensure
      - run:
          name: Unit tests
          command: go test -v ./...
